base_url = "https://api.notion.com/v1/{endpoint}"

list_of_fields = {
    'document_db': ['Name',
                    'Status',
                    'Counter',
                    'QCer',
                    'Goal',
                    'Date (Start)',
                    'Created at (End Date)',
                    'Template Name',
                    'Batch Process',
                    'Granularity Level',
                    'QCed?',
                    'Type of Doc',
                    'Nature of Doc',
                    'Treatments(s)?',
                    'DwCA',
                    'Why no DwCA?',
                    'Text Dec Problem?',
                    'Fig Dec Problem?',
                    'Incorrect Treats',
                    'Missed Keys',
                    'Missed Treats',
                    'Spurious Treats',
                    'Missed n. spp.',
                    'Incomplete Keys',
                    'Missed Figures',
                    'Incorrect Figures',
                    'Fig Missed Labels',
                    'Incomp Captions',
                    'Missed Tables',
                    'Missed bibRefs',
                    'Deg Miss treatCits',
                    'Def Miss matCits',
                    'Suppl. Files',
                    'Hs to DwCA',
                    'Hs Counting Errors',
                    'Hs to Gran Level',
                    'Hs Fix QC Errors',
                    'UUID',
                    'Zenodo Link',
                    'Hs Fix ExtQC',
                    'Hs PreQC'
                ],
    'batch_db': ['Name',
                 'Status',
                 'Creator',
                 'Counter',
                 'QCer',
                 'Batch Type',
                 '(A) Date  (Start-End)',
                 '(A) Templates Used',
                 '(A) Docs Processed',
                 'Updated']
}